language: ruby
services:
  - redis-server
rvm:
  - 2.1.2
before_script:
  - cp spec/database.yml config/database.yml
  - psql -c 'create database tiny_listing_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test
